# DataSource configuration
spring:
  application:
    name: HOTEL-SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ocean@666#

# JPA and Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

# Server configuration
server:
  port: 8082
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka