## DataSource configuration
spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ocean@666#

# JPA and Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server configuration
server:
  port: 8081
#  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
 
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*" #"shutdown, health, info"
  endpoint:
    helath:
      show-details: true
    shutdown:
      enabled: true
#    info:
#       enabled:false


      
# Spring Boot Application Configuration
#spring:
#  application:
#    name: USER-SERVICE
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: ${DB_USERNAME:postgres}  # Use environment variables for security
#    password: ${DB_PASSWORD:probuddy}
#
#    # HikariCP Connection Pooling (Recommended for better performance)
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 2
#      idle-timeout: 30000
#      pool-name: HikariCP-Pool
#
#  # JPA and Hibernate settings
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
## Server Configuration
#server:
#  port: 8081

# Eureka Client Configuration
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}  # Unique instance ID
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

