# DataSource configuration
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/free
    username: microservice
    password: hrms

# JPA and Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      database-platform: org.hibernate.dialect.Oracle12cDialect

# Server configuration
server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
application:
  name: RATING-SERVICE