# DataSource configuration
spring:
  application:
    name: RATING-SERVICE
  config:
    import: configserver:http://localhost:8085 # Config Server URI

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ocean@666#

# JPA and Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

# Server configuration
server:
  port: 8083

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
